[[repos]]
repo = "local"

[[repos.hooks]]
id = "prec-bsl"
name = "prec-bsl"
entry = "/home/alko/develop/open-source/prec-bsl/target/release/prec-bsl prek-hook"
language = "system"
always_run = true
pass_filenames = false
args = [
  "--config",
  "v8config.json",
  "--rules",
  "ВставкаКопирайтов,ДобавлениеПробеловПередКлючевымиСловами,ЗапретИспользованияПерейти,ИсправлениеНеКаноническогоНаписания,ПроверкаДублейПроцедурИФункций,ПроверкаКорректностиИнструкцийПрепроцессора,ПроверкаКорректностиОбластей,УдалениеЛишнихКонцевыхПробелов,УдалениеЛишнихПустыхСтрок",
]
