[[repos]]
repo = "https://github.com/alkoleft/prec-bsl"
rev = "v0.1.1"

[[repos.hooks]]
id = "prec-bsl"
args = [
  "--config",
  "v8config.json",
  "--rules",
  "ВставкаКопирайтов,ДобавлениеПробеловПередКлючевымиСловами,ЗапретИспользованияПерейти,ИсправлениеНеКаноническогоНаписания,ПроверкаДублейПроцедурИФункций,ПроверкаКорректностиИнструкцийПрепроцессора,ПроверкаКорректностиОбластей,УдалениеЛишнихКонцевыхПробелов,УдалениеЛишнихПустыхСтрок",
]
